<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserCrudController extends \Backpack\PermissionManager\app\Http\Controllers\UserCrudController
{
    public function setup()
    {
        parent::setup(); // TODO: Change the autogenerated stub

        $this->crud->addField([    // SELECT2
            'label'         => 'Vocational Training Institute',
            'type'          => 'select2',
            'name'          => 'vti_id',
            'entity'        => 'vti',
            'attribute'     => 'name',
            'model'         => "App\Models\Vti",
        ]);

        $this->crud->addColumn([

        ])


        if (!backpack_user()->hasRole('admin')) {

            $this->crud->removeFields(['roles_and_permissions']);
        }
    }

}
