<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserCrudController extends \Backpack\PermissionManager\app\Http\Controllers\UserCrudController
{
    public function setup()
    {
        parent::setup(); // TODO: Change the autogenerated stub

        $this->crud->addField([    // SELECT2
            'label'         => 'Vocational Training Institute',
            'type'          => 'select2',
            'name'          => 'vti_id',
            'entity'        => 'vti',
            'attribute'     => 'name',
            'model'         => "App\Models\Vti",
            'options'   => backpack_user()->hasRole('vti') ? (function ($query) {
                return $query->where('id', backpack_user()->vti_id)->get();
            }) : (function ($query) {
                return $query->orderBy('name', 'desc')->get();
            }),
        ]);

        /*$this->crud->addColumn([

        ]);*/

        if (!backpack_user()->hasRole('admin')) {

            $this->crud->removeFields(['roles_and_permissions']);
        }
    }

}
